services:
  pdf-to-md-api:
    build: ./backend
    container_name: pdf-to-md-api
    ports:
      - "8000:8000"
    restart: unless-stopped

  pdf-to-md-front:
    image: nginx:alpine
    container_name: pdf-to-md-front
    ports:
      - "8079:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    restart: unless-stopped

  pdf-to-md-tests:
    build: ./backend
    container_name: pdf-to-md-tests
    # command: pytest --cov=app --cov-report=term-missing --cov-fail-under=80
    command: pytest --cov=app --cov-report=html --cov-report=term-missing --cov-fail-under=80
    volumes:
      - ./backend:/app
    profiles:
      - test
